language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: components.language_detector.LanguageDetector
    model_path: "components/lid.176.bin"
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: ResponseSelector
  - name: components.response_translator.ResponseTranslator

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
